import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Navigation from './components/Navigation'
import Hero from './components/Hero'
import Logo from './../public/fayne-pharmacy-logo.ico'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href={Logo.src} />
      </Head>
      <Navigation />
      <Hero />
    </>
  )
}
